package com.drpeng.worklog.dao;


import com.drpeng.worklog.model.DailyReport;

public interface DailyReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_report
     *
     * @mbg.generated
     */
    int insert(DailyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_report
     *
     * @mbg.generated
     */
    int insertSelective(DailyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_report
     *
     * @mbg.generated
     */
    DailyReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DailyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DailyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DailyReport record);
}